# Created in Flutter 3.7.11
# Release Command for web: flutter build web --web-renderer html --release
# Change app icon Command: flutter pub run flutter_launcher_icons

name: fluttertemplate
description: Flutter templated architecture

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0
  firebase_analytics: ^10.2.0
  firebase_messaging: ^14.4.0
  firebase_crashlytics: ^3.1.0
  connectivity_plus: ^3.0.4
  dio: ^5.1.1
  google_fonts: ^4.0.3
  intl: ^0.17.0
  package_info_plus: ^3.1.0
  shared_preferences: ^2.1.0
  flutter_dotenv: ^5.0.2
  get_it: ^7.2.0
  go_router: ^6.5.6
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pretty_dio_logger: ^1.3.1
  flutter_launcher_icons: ^0.13.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#f93523"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - .env
