// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz6w-LjTDK8we-3tKpruLbJB3BpNsyeJo',
    appId: '1:1039493296135:android:bd05e948f9b006a9353aa2',
    messagingSenderId: '1039493296135',
    projectId: 'structured-project-flutter',
    storageBucket: 'structured-project-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCORuPdP-YuBACx-m_GC90P8HeP4JNzJRw',
    appId: '1:1039493296135:ios:d0de1f7a8bb453e6353aa2',
    messagingSenderId: '1039493296135',
    projectId: 'structured-project-flutter',
    storageBucket: 'structured-project-flutter.appspot.com',
    iosClientId: '1039493296135-ke3gr21vpjn2r1t1dfk3dmtpk0l8747r.apps.googleusercontent.com',
    iosBundleId: 'com.farhaz.fluttertemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCORuPdP-YuBACx-m_GC90P8HeP4JNzJRw',
    appId: '1:1039493296135:ios:d0de1f7a8bb453e6353aa2',
    messagingSenderId: '1039493296135',
    projectId: 'structured-project-flutter',
    storageBucket: 'structured-project-flutter.appspot.com',
    iosClientId: '1039493296135-ke3gr21vpjn2r1t1dfk3dmtpk0l8747r.apps.googleusercontent.com',
    iosBundleId: 'com.farhaz.fluttertemplate',
  );
}
